version: '3.8'
services:
  api-gateway:
    build: ./api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - user-service
      - product-service
      - order-service
      - payment-service

  user-service:
    build: ./user-service
    ports:
      - "8083:8080"

  product-service:
    build: ./product-service
    ports:
      - "8081:8080"

  order-service:
    build: ./order-service
    ports:
      - "8082:8080"

  payment-service:
    build: ./payment-service
    ports:
      - "8084:8080"
