services:
  api-gateway:
    build:
      context: .
      dockerfile: api-gateway/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - user-service
      - product-service
      - order-service
      - payment-service

  product-service:
    build:
      context: .
      dockerfile: product-service/Dockerfile
    ports:
      - "8081:8080"

  order-service:
    build:
      context: .
      dockerfile: order-service/Dockerfile
    ports:
      - "8082:8080"

  user-service:
    build:
      context: .
      dockerfile: user-service/Dockerfile
    ports:
      - "8083:8080"

  payment-service:
    build:
      context: .
      dockerfile: payment-service/Dockerfile
    ports:
      - "8084:8080"
